export const SKILL_NAMES = {
  JS: 'JavaScript',
  REACT: 'React',
  REACT_NATIVE: 'React Native',
  NODE: 'Node',
  EXPRESS: 'Express',
  REDUX: 'Redux',
  VUE: 'Vue',
  STYLED_COMPONENTS: 'Styled Components',
  MONGO: 'MongoDB',
  POSTGRESQL: 'PostgreSQL',
  APOLLO: 'Apollo',
  THREE: 'Three.js',
  GQL: 'GraphQL',
  SQL: 'SQL',
  C_SHARP: 'C#',
  GO: 'GoLang',
  UNITY: 'Unity3D',
  ELECTRON: 'Electron',
  JEST: 'Jest',
  ENZYME: 'Enzyme',
  MOCHA: 'Mocha',
  CHAI: 'Chai',
  MY_SQL: 'MySQL',
  TS: 'TypeScript',
  SASS: 'Sass',
  ETHEREUM: 'Ethereum',
  JQUERY: 'jQuery',
  DOCKER: 'Docker',
  K8S: 'Kubernetes',
  AWS: 'AWS',
  AZURE: 'Azure DevOps',
  HTML: 'HTML',
  CSS: 'CSS',
  NEXT: 'Next.js',
};

export const SKILL_TYPES = {
  LANGUAGES: 'Languages',
  LIB: 'Libraries / Frameworks',
  CSS: 'CSS',
  DB: 'Databases',
  NATIVE: 'Native apps',
  TEST: 'Testing',
  DEV_OPS: 'Dev Ops / Deployments',
};

export const SKILL_LEVELS = {
  HALO: 'A_HALO',
  SMILE: 'B_SMILE',
  FLUSHED: 'C_FLUSHED',
};
