export const SKILL_NAMES = {
  JS: 'JavaScript',
  REACT: 'React',
  REACT_NATIVE: 'React Native',
  NODE: 'Node',
  EXPRESS: 'Express',
  REDUX: 'Redux',
  VUE: 'Vue',
  STYLED_COMPONENTS: 'Styled Components',
  MONGO: 'MongoDB',
  POSTGRESQL: 'PostgreSQL',
  APOLLO: 'Apollo',
  THREE: 'Thress.js',
  GQL: 'GraphQL',
  SQL: 'SQL',
  C_SHARP: 'C#',
  GO: 'GoLang',
  UNITY: 'Unity3D',
  ELECTRON: 'Electron',
  JEST: 'Jest',
  ENZYME: 'Enzyme',
  MOCHA: 'Mocha / Chai',
  TS: 'Typescript',
  SASS: 'Sass',
  ETHEREUM: 'Ethereum',
  JQUERY: 'jQuery',
  DOCKER: 'Docker',
  K8S: 'Kubernetes',
  AWS: 'AWS',
  AZURE: 'Azure DevOps',
  XCODE: 'Xcode',
  ANDROID: 'Android Studio',
  HTML: 'HTML',
  CSS: 'CSS',
};

export const SKILL_TYPES = {
  LANGUAGES: 'Languages',
  FE: 'Frontend',
  BE: 'Backend',
  FE_FRAMEWORK: 'Frontend frameworks',
  BE_FRAMEWORK: 'Backend frameworks',
  JS_LIB: 'Libraries',
  CSS: 'CSS',
  DB: 'Databases',
  NATIVE: 'Mobile / Desktop apps',
  TEST: 'Testing',
  DEV_OPS: 'Dev Ops / Deployments',
  IOS: 'iOS',
  ANDROID: 'Android',
};

export const SKILL_KEYWORDS = {
  JS: 'javascript js',
  GQL: 'graphql gql',
  SQL: 'sql',
  VR: 'virtual reality vr',
  IOS: 'apple ios',
  ANDROID: 'android',
  UNITY: 'unity3d',
  BLOCKCHAIN: 'blockchain cryptocurrency',
  FE: 'frontend fe',
  BE: 'backend end',
  THREE_D: '3d',
};

export const SKILL_LEVELS = {
  HALO: 'A_HALO',
  SMILE: 'B_SMILE',
  FLUSHED: 'C_FLUSHED',
};
